// Generated by CoffeeScript 1.6.3
(function() {
  var Cache, expect;

  expect = require('chai').expect;

  Cache = require('../../../lib/Cache');

  describe('Cache', function() {
    return describe('#constructor()', function() {
      return it('should throw an error if storage is not an instance of Cache Storage', function() {
        return expect(function() {
          return new Cache(new Array);
        }).to["throw"](Error);
      });
    });
  });

}).call(this);
