// Generated by CoffeeScript 1.6.3
(function() {
  require('./Cache');

  require('./FileStorage');

  require('./BrowserLocalStorage');

  require('./DevNullStorage');

  require('./MemoryStorage');

}).call(this);
