// Generated by CoffeeScript 1.6.3
(function() {
  var DevNullSyncStorage, Storage, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Storage = require('./Storage');

  DevNullSyncStorage = (function(_super) {
    __extends(DevNullSyncStorage, _super);

    function DevNullSyncStorage() {
      _ref = DevNullSyncStorage.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    DevNullSyncStorage.prototype.async = false;

    DevNullSyncStorage.prototype.getData = function() {
      return {};
    };

    DevNullSyncStorage.prototype.getMeta = function() {
      return {};
    };

    DevNullSyncStorage.prototype.writeData = function(data, meta) {
      return this;
    };

    DevNullSyncStorage.prototype.read = function(key) {
      return null;
    };

    DevNullSyncStorage.prototype.write = function(key, data, dependencies) {
      if (dependencies == null) {
        dependencies = {};
      }
      return this;
    };

    DevNullSyncStorage.prototype.remove = function(key) {
      return this;
    };

    return DevNullSyncStorage;

  })(Storage);

  module.exports = DevNullSyncStorage;

}).call(this);
