// Generated by CoffeeScript 1.6.3
(function() {
  var Cache, FileStorage, Storage, fs, path,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Storage = require('./Storage');

  Cache = require('../Cache');

  fs = null;

  path = null;

  FileStorage = (function(_super) {
    __extends(FileStorage, _super);

    FileStorage.prototype.directory = null;

    function FileStorage(directory) {
      this.directory = directory;
      if (typeof window !== 'undefined') {
        throw new Error('FileStorage: Can not use this storage in browser');
      }
      fs = require('fs');
      path = require('path');
      this.directory = path.resolve(this.directory);
      if (!fs.existsSync(this.directory)) {
        throw new Error('FileStorage: directory ' + this.directory + ' does not exists');
      }
      if (!fs.statSync(this.directory).isDirectory()) {
        throw new Error('FileStorage: path ' + this.directory + ' must be directory');
      }
    }

    FileStorage.prototype.getFileName = function() {
      return this.directory + '/__' + this.cache.namespace + '.json';
    };

    FileStorage.prototype.getData = function() {
      var data, file;
      if (this.data === null) {
        file = this.getFileName();
        if (fs.existsSync(file)) {
          data = JSON.parse(fs.readFileSync(file, {
            encoding: 'utf8'
          }));
          this.data = data.data;
          this.meta = data.meta;
        } else {
          this.data = {};
          this.meta = {};
        }
      }
      return this.data;
    };

    FileStorage.prototype.writeData = function(data, meta) {
      var file;
      this.data = data;
      this.meta = meta;
      file = this.getFileName();
      fs.writeFileSync(file, JSON.stringify({
        data: this.data,
        meta: this.meta
      }));
      return this;
    };

    return FileStorage;

  })(Storage);

  module.exports = FileStorage;

}).call(this);
