// Generated by CoffeeScript 1.6.3
(function() {
  var BrowserLocalStorage, Cache, expect;

  expect = require('chai').expect;

  Cache = require('../../../../../lib/Cache');

  BrowserLocalStorage = require('../../../../../Storage/BrowserLocalSyncStorage');

  describe('BrowserLocalSyncStorage', function() {
    return describe('#constructor()', function() {
      return it('should throws an error if local storage is not supported', function() {
        return expect(function() {
          return new BrowserLocalStorage;
        }).to["throw"](Error);
      });
    });
  });

}).call(this);
