// Generated by CoffeeScript 1.6.3
(function() {
  var BaseStorage, Cache, Storage, isWindow, moment, path, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  isWindow = typeof window === 'undefined' ? false : true;

  if (!isWindow) {
    path = require('path');
  }

  BaseStorage = require('../Storage');

  moment = require('moment');

  Cache = require('../../Cache');

  Storage = (function(_super) {
    __extends(Storage, _super);

    function Storage() {
      _ref = Storage.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Storage.prototype.async = true;

    Storage.prototype.read = function(key, fn) {
      var _this = this;
      return this.getData(function(data) {
        if (typeof data[key] === 'undefined') {
          return fn(null);
        } else {
          return _this.findMeta(key, function(meta) {
            if (_this.verify(meta[key])) {
              return fn(data[key]);
            } else {
              return _this.remove(key, function() {
                return fn();
              });
            }
          });
        }
      });
    };

    Storage.prototype.write = function(key, data, dependencies, fn) {
      var _this = this;
      if (dependencies == null) {
        dependencies = {};
      }
      return this.getData(function(all) {
        all[key] = data;
        return _this.getMeta(function(meta) {
          meta[key] = dependencies;
          return _this.writeData(all, meta, function() {
            return fn();
          });
        });
      });
    };

    Storage.prototype.remove = function(key, fn) {
      var _this = this;
      return this.getData(function(data) {
        return _this.getMeta(function(meta) {
          if (typeof data[key] !== 'undefined') {
            delete data[key];
            delete meta[key];
          }
          return _this.writeData(data, meta, function() {
            return fn();
          });
        });
      });
    };

    Storage.prototype.clean = function(conditions) {
      var key, tag, type, typeFn, _i, _j, _k, _len, _len1, _len2, _ref1, _ref2, _ref3;
      typeFn = Object.prototype.toString;
      type = typeFn.call(conditions);
      if (conditions === Cache.ALL) {
        this.writeData({}, {});
      } else if (type === '[object Object]') {
        if (typeof conditions[Cache.TAGS] !== 'undefined') {
          if (typeFn(conditions[Cache.TAGS]) === '[object String]') {
            conditions[Cache.TAGS] = [conditions[Cache.TAGS]];
          }
          _ref1 = conditions[Cache.TAGS];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            tag = _ref1[_i];
            _ref2 = this.findKeysByTag(tag);
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              key = _ref2[_j];
              this.remove(key);
            }
          }
        }
        if (typeof conditions[Cache.PRIORITY] !== 'undefined') {
          _ref3 = this.findKeysByPriority(conditions[Cache.PRIORITY]);
          for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
            key = _ref3[_k];
            this.remove(key);
          }
        }
      }
      return this;
    };

    Storage.prototype.findMeta = function(key, fn) {
      return this.getMeta(function(meta) {
        if (typeof meta[key] !== 'undefined') {
          return fn(meta[key]);
        } else {
          return fn(null);
        }
      });
    };

    Storage.prototype.findKeysByTag = function(tag, fn) {
      return this.getMeta(function(metas) {
        var key, meta, result;
        result = [];
        for (key in metas) {
          meta = metas[key];
          if (typeof meta[Cache.TAGS] !== 'undefined' && meta[Cache.TAGS].indexOf(tag) !== -1) {
            result.push(key);
          }
        }
        return fn(result);
      });
    };

    Storage.prototype.findKeysByPriority = function(priority, fn) {
      return this.getMeta(function(metas) {
        var key, meta, result;
        result = [];
        for (key in metas) {
          meta = metas[key];
          if (typeof meta[Cache.PRIORITY] !== 'undefined' && meta[Cache.PRIORITY] <= priority) {
            result.push(key);
          }
        }
        return fn(result);
      });
    };

    Storage.prototype.verify = function(meta) {
      var file, item, mtime, time, typefn, _i, _len, _ref1, _ref2, _ref3;
      typefn = Object.prototype.toString;
      if (typefn.call(meta) === '[object Object]') {
        if (typeof meta[Cache.FILES] !== 'undefined') {
          this.checkFilesSupport();
          if (isWindow) {
            _ref1 = meta[Cache.FILES];
            for (file in _ref1) {
              time = _ref1[file];
              mtime = window.require.getStats(file).mtime;
              if (mtime === null) {
                throw new Error('File stats are disabled in your simq configuration. Can not get stats for ' + file + '.');
              }
              if (window.require.getStats(file).mtime.getTime() !== time) {
                return false;
              }
            }
          } else {
            _ref2 = meta[Cache.FILES];
            for (file in _ref2) {
              time = _ref2[file];
              if ((new Date(Cache.getFs().statSync(file).mtime)).getTime() !== time) {
                return false;
              }
            }
          }
        }
        if (typeof meta[Cache.EXPIRE] !== 'undefined') {
          if (moment().valueOf() >= meta[Cache.EXPIRE]) {
            return false;
          }
        }
        if (typeof meta[Cache.ITEMS] !== 'undefined') {
          if (this.async) {
            throw new Error('Expiration by items is currently not supported in async storages.');
          }
          _ref3 = meta[Cache.ITEMS];
          for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
            item = _ref3[_i];
            item = this.findMeta(item);
            if ((item === null) || (item !== null && this.verify(item) === false)) {
              return false;
            }
          }
        }
      }
      return true;
    };

    Storage.prototype.parseDependencies = function(dependencies) {
      var file, files, i, item, mtime, result, time, typefn, _i, _j, _k, _len, _len1, _len2, _ref1, _ref2, _ref3;
      typefn = Object.prototype.toString;
      result = {};
      if (typefn.call(dependencies) === '[object Object]') {
        if (typeof dependencies[Cache.FILES] !== 'undefined') {
          this.checkFilesSupport();
          files = {};
          if (isWindow) {
            _ref1 = dependencies[Cache.FILES];
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              file = _ref1[_i];
              mtime = window.require.getStats(file).mtime;
              if (mtime === null) {
                throw new Error('File stats are disabled in your simq configuration. Can not get stats for ' + file + '.');
              }
              file = window.require.resolve(file);
              files[file] = mtime.getTime();
            }
          } else {
            _ref2 = dependencies[Cache.FILES];
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              file = _ref2[_j];
              file = path.resolve(file);
              files[file] = (new Date(Cache.getFs().statSync(file).mtime)).getTime();
            }
          }
          result[Cache.FILES] = files;
        }
        if (typeof dependencies[Cache.EXPIRE] !== 'undefined') {
          switch (typefn.call(dependencies[Cache.EXPIRE])) {
            case '[object String]':
              time = moment(dependencies[Cache.EXPIRE], Cache.TIME_FORMAT);
              break;
            case '[object Object]':
              time = moment().add(dependencies[Cache.EXPIRE]);
              break;
            default:
              throw new Error('Expire format is not valid');
          }
          result[Cache.EXPIRE] = time.valueOf();
        }
        if (typeof dependencies[Cache.ITEMS] !== 'undefined') {
          result[Cache.ITEMS] = [];
          _ref3 = dependencies[Cache.ITEMS];
          for (i = _k = 0, _len2 = _ref3.length; _k < _len2; i = ++_k) {
            item = _ref3[i];
            result[Cache.ITEMS].push(this.cache.generateKey(item));
          }
        }
        if (typeof dependencies[Cache.PRIORITY] !== 'undefined') {
          result[Cache.PRIORITY] = dependencies[Cache.PRIORITY];
        }
        if (typeof dependencies[Cache.TAGS] !== 'undefined') {
          result[Cache.TAGS] = dependencies[Cache.TAGS];
        }
      }
      return result;
    };

    return Storage;

  })(BaseStorage);

  module.exports = Storage;

}).call(this);
